In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
def initialize_center(X,n):
  # Randomly choose n samples from X
  return np.array(X[np.random.choice(X.shape[0],n,replace=False)])

In [0]:
def compute_center(X):
  # Computing center of X
  return np.mean(X,axis=0)

In [0]:
def distance(a,b, norm=2):
  """
  Compute the distance between a and b with norm
  
  Parameters:
    a,b - np.array : two points that need to be compute the distance between them
    norm - int : the norm - default = 2
    
  Returns:
    the distance
  """
  tmp = a - b
  if norm == 1:
    return sum(np.abs(tmp))
  else:
    return np.power(sum(np.power(tmp,norm)),1./norm)

In [0]:
def assign_k(X,centers):
  # Assign cluster index for each data point
  targets = np.zeros(X.shape[0])
  for target,sample in zip(targets,X):
    distances = np.array([distance(sample,center) for center in centers])
    target = np.argmin(distances)
  return targets

In [0]:
def update_center(targets,X,n_clusters):
  # Update new centers
  centers = np.zeros((n_cluster,X.shape[1]))
  for i in range(n_clusters):
    cluster = X[targets == i]
    centers[i] = compute_center(cluster)
  return centers

In [0]:
def k_mean(X,n_clusters):
  centers = initialize_center(X,n_clusters)
  centers_L = []
  centers_L.append(centers)
  for i in range(10):
    targets = assign_k(X,centers)
    new_centers = update_center(targets,X,n_clusets)
    centers_L.append(new_centers)
  return centers_L, targets

In [41]:
X = np.random.normal(0,1,(5,3))
print(X)
centers = initialize_center(X,2)
targets = np.array([2,1,2,1,2])
X[targets == 2]

[[-0.82113259  0.22720738 -0.4291594 ]
 [-1.74676075 -1.41374699 -0.3872331 ]
 [ 1.2197304  -1.34008439  0.11121919]
 [ 1.44062011  1.73469289  0.11107693]
 [ 0.15264403  0.4998098  -1.07986285]]


array([[-0.82113259,  0.22720738, -0.4291594 ],
       [ 1.2197304 , -1.34008439,  0.11121919],
       [ 0.15264403,  0.4998098 , -1.07986285]])

In [42]:
np.zeros(4)

array([0., 0., 0., 0.])